main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.8.2
api-version: 1.13
name: TreeFeller
softdepend: [MCMMO,GriefProtection]
commands:
    treefeller:
        description: Reloads the tree feller or toggles debug mode
        usage: /treefeller reload|debug [on|off]