main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.6
api-version: 1.13
name: TreeFeller
softdepend: [MCMMO]
commands:
    treefeller:
        description: Reloads the tree feller
        usage: /treefeller reload